### PR TITLE
Blacklist gulp-static-site-generator

### PR DESCRIPTION
**Pull request by strugee**
I've written a project, https://github.com/straticjs, that will do the same thing but in an idiomatic gulp way (the project consists of many modules and a Yeoman generator). I'm reluctant to suggest it as a replacement in this blacklist entry for fear of being too opinionated, etc., but I'd be happy to change it if desired ;)

### CODE REVIEW

**Comment by strugee** [comment]
FYI @simbo

**Comment by simbo** [comment]
I don't see what your project has to do with blacklisting gulp-static-site-generator. (like the existence of any one of hundreds of static site generators out there would be a reason to deprecate another one...)

Regarding your described reason "does too much": this is exactly the reason why this plugin exists - because generating a static site with gulp plugins can be a complex and time-consuming approach. This plugin has everything wired together and in the end, it *does one thing* - generating a static site...

**Comment by contra** [comment]
Creating something new doesn't mean you get to add everyone else to the blacklist.

Blacklist is for duplicates, broken modules, stuff that breaks the vinyl spec, etc.

**Comment by strugee** [comment]
@contra @simbo as I said earlier, admittedly buried in the diff, I didn't submit this to the blacklist because of my project, I submitted it because it "does too many things" - reasoning we've applied to many plugins already. https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md says, do **one thing**. The problem with this module is that it does many: it compiles Jade, it renders Markdown, parses frontmatter, etc.

Again, sorry for the confusion caused by mentioning my project - I wasn't saying that had anything to do with why I think this module should be blacklisted, just pointing out an alternative approach that solves the problems with this module. (IMHO, obviously.)

**Comment by phated** [comment]
@strugee I think that you are right about not doing 1 thing but approaching it in a way that promotes your project is what got this closed.  I'll put this on my backlog to review in the future.

**Comment by strugee** [comment]
@phated right, totally understand - didn't mean to seem like I was promoting my project (that's why I didn't mention it in the actual diff). Do you want to reopen in the meantime?

**Pull request closed without merging**
