### PR TITLE
Replace abandoned dependency

### PR DESCRIPTION
**Pull request by leo**
Since [gulp-livereload](https://github.com/vohof/gulp-livereload) doesn't seem to be maintained anymore, I've decided to fork the repo and update its contents: [gulp-refresh](https://github.com/leo/gulp-refresh). A lot of others have already made the switch, too.

@contra Would be awesome if you could add me as a collaborator to this part of the gulp website, too (since I'm already keeping [gulpjs.github.io](https://github.com/gulpjs/gulpjs.github.io) up to date).

### CODE REVIEW

**Comment by contra** [comment]
@leo when did @vohof say it wasn't maintained?

If this is actually the case, it should also be noted in the blacklist

**Comment by leo** [comment]
@contra He never said that. I was assuming it since his last commit is half a year old. He also doesn't seem to have time to close issues/PRs and I simply didn't wanted it do die, since I'll be using it in a lot of my projects. So I've decided to fork it and work it.

I'm even planning to re-add him as collaborator if he decides to start working on it again. So all in all, it's the best for all of us, I guess!

**Comment by leo** [comment]
> it should also be noted in the blacklist

Done!

**Comment by phated** [comment]
Sometimes maintainers get busy (see: gulp); did you ask the maintainer if they'd be willing to add you to the project to avoid forking the community?

**Comment by leo** [comment]
@phated Before forking it, I've looked at this GitHub profile, his Twitter account and even checked his website and the `package.json` of `gulp-livereload`. None of them included a way through which I could have contacted him. And since he also hasn't tweeted anything since October last year, I've decided to fork it.

**Comment by phated** [comment]
@leo you should definitely open an issue but all git commits have an email attached, just run `git log` I believe.

**Comment by leo** [comment]
@phated Good to know! Also just noticed that there's one on this npm profile.

https://github.com/vohof/gulp-livereload/issues/113

**Comment by phated** [comment]
Cool, thanks

**Comment by nemoDreamer** [comment]
:+1: for Github messaging anyone? :laughing:

**Comment by leo** [comment]
@nemoDreamer ?! :smile:

**Pull request merged**
