### PR TITLE
Blacklist gulp-es6to5

### PR DESCRIPTION
**Pull request by arthurvr**
Duplicate of [gulp-6to5](https://www.npmjs.com/package/gulp-6to5/).

### CODE REVIEW

**Comment by phated** [comment]
We should probably blacklist 6to5 and point to gulp-babel since they changed their name.

**Comment by sindresorhus** [comment]
Also open an issue on the plugins issue tracker about this being blacklisted.

**Comment by arthurvr** [comment]
> Also open an issue on the plugins issue tracker about this being blacklisted.

Done! https://github.com/christophehurpeau/gulp-es6to5/issues/1

> We should probably blacklist 6to5 and point to gulp-babel since they changed their name.

opening another PR

**Comment by arthurvr** [comment]
For some reason gulp-babel doesn't show up on the site.

**Comment by sindresorhus** [comment]
@arthurvr https://github.com/gulpjs/plugins/issues/156#issuecomment-69546537

**Pull request merged**
